# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'reactAuth0' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for reactAuth0

  target 'reactAuth0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# Auth0 Lock

pod 'Lock', '~> 2.2'
pod 'Auth0', '~> 1.5'
